---
development:
  cloud_name: deqorjmzl
  api_key: <%= ENV['CLD_KEY'] %>
  api_secret: <%= ENV['CLD_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: deqorjmzl
  api_key: <%= ENV['CLD_KEY'] %>
  api_secret:  <%= ENV['CLD_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: deqorjmzl
  api_key:  <%= ENV['CLD_SECRET'] %>
  api_secret:  <%= ENV['CLD_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
